#!/usr/bin/env bash
# COMMENTSSSSSS
if [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "school file is not empty"
		if [ -f "school" ]
		then
			echo "school is a regular file"
		fi	
	else
		echo "school file is empty"
	fi	
else
	echo "school file does not exist"
fi
